### ISSUE TITLE
Colon Inside String

### ISSUE THREAD

**Issue by benhamill** [IN3D/vim-raml#1]
In have this snippet in a RAML file:

```
types:
  # ...
  VenueHours:
    type: string[]
    examples:
      - content: ["08:00", "17:30"]
      - content: ["09:00", "20:00"]
```

Everything after the first `:` in the next-to-last line (the middle of `"08:00"`) is cyan (in case that's highly dependent on color scheme, its the same color as any quoted string. Seems the colon and quotes is confusing the highlighting?

Similarly, above that, I have this:

```
types:
  # ...
  Region:
    properties:
      # ...
      utc_offset:
        type: string
        examples:
          - content: +03:30
          - content: -06:00
```

In those two examples, the `+03` and `-06` are blue like a key (same color as `content` or `type`), the `:` is red (same as the `:` after `content` or `type`) and the `30` and `00` are light blue like a quoted string.

These problems don't show up if I manually `:set ft=yaml`.

Let me know if there's anything else I can provide to help debug this.

**Comment by benhamill** [comment]
Here's a minimal document to display the weirdness:

``` yaml
#%RAML 1.0
types:
  Foo:
    properties:
      bar:
        type: string
        example: +03:00
      baz:
        type: string[]
        example: ["08:00", "17:30"]
  ThisStuffShouldn'tBeLightBlue:
    properties:
      right?: right
```
