### ISSUE TITLE
Optional Key Name Highlighting

### ISSUE THREAD

**Issue by benhamill** [IN3D/vim-raml#2]
In the [RAML 1.0rc2 spec](https://github.com/raml-org/raml-spec/blob/raml-10-rc2/versions/raml-10/raml-10.md), in [the section about syntactic sugar](https://github.com/raml-org/raml-spec/blob/raml-10-rc2/versions/raml-10/raml-10.md#shortcuts-and-syntactic-sugar), it says you can skip the `required` facet for a property and instead append a `?` to the property's name.

For example, this:

``` yaml
Person:
  properties:
    nick?: string
```

is equivalent to this:

```
Person:
  type: object
  properties:
    nick:
      type: string
      required: false
```

But the syntax highlighting from this plugin seems very confused about this fact and the `?` makes the key not colored like other property keys.
