### ISSUE TITLE
Basic Type Names in String

### ISSUE THREAD

**Issue by benhamill** [IN3D/vim-raml#3]
If I'm defining a type like this:

``` yaml
Person:
  properties:
    age:
      type: integer
      description: |
        The number of years the person has been alive.
```

The word "number" is highlighted the same as the word "integer" above it, but "number" is just part of a string. If I inline the description (to `description: The number of years the person has been alive.`), it is also highlighted as if it were the name of a type. If I wrap it in double quotes, it highlights all the words in the description the same.
