### ISSUE TITLE
Multiline String Coloring

### ISSUE THREAD

**Issue by benhamill** [IN3D/vim-raml#4]
It looks like strings are handled differently depending on whether they're quoted, vs literal, folded or unquoted. For example:

``` yaml
description: |
  foo
description: >
  foo
description: foo
description: "foo"
description: 'foo'
```

In this, the values in the last two keys will be one color and the values of the first 3 keys will be another.

I'm not sure what you can do about that middle (unquoted) one without targeting the `description` key specifically, but I think you can safely treat the `|` and `>` glyphs as introducing a string and bailing on other highlighting rules until indentation changes (or lessens? Not sure).
